version: '3.8'

services:
 user-posts-api-serverless:
  container_name: '${LOCALSTACK_DOCKER_NAME:-user-posts-api-serverless}'
  image: localstack/localstack
  env_file: ./config/local.env
  ports:
   - 4566:4566
   - 4571:4571
   - 4510-4559:4510-4559 # external services port range
  volumes:
   - '${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack'
   - '/var/run/docker.sock:/var/run/docker.sock'
