service: user-posts-api-serverless
frameworkVersion: '3'

plugins:
  - serverless-offline
  - serverless-plugin-typescript

provider:
  name: aws
  runtime: nodejs16.x
  region: ${opt:region, self:custom.region}
  stage: ${opt:stage, self:custom.defaultStage}
  environment:
    POSTS_API_URL: ${env:POSTS_API_URL}
    USERS_API_URL: ${env:USERS_API_URL}

functions:
  get-user-posts: ${file(src/infrastructure/functions/get-user-posts/serverless.yml)}
